[package]
name = "test_solana"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.1"
thiserror = "1.0.61"
spl-token = {version = "4.0.1", features = ["no-entrypoint"]}
arrayref = "0.3.6"

[lib]
crate-type = ["cdylib", "lib"]
